"""empty message

Revision ID: 04b065f92762
Revises: 
Create Date: 2024-05-12 10:24:57.383709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b065f92762'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminreg',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_username', sa.String(length=20), nullable=False),
    sa.Column('admin_pwd', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('admin_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_fname', sa.String(length=64), nullable=False),
    sa.Column('user_lname', sa.String(length=64), nullable=False),
    sa.Column('user_add', sa.String(length=200), nullable=False),
    sa.Column('user_city', sa.String(length=64), nullable=False),
    sa.Column('user_zipcode', sa.DateTime(), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=False),
    sa.Column('user_phone', sa.String(length=50), nullable=True),
    sa.Column('user_profile', sa.String(length=300), nullable=True),
    sa.Column('user_pix', sa.String(length=120), nullable=True),
    sa.Column('user_username', sa.String(length=100), nullable=False),
    sa.Column('user_state', sa.String(length=100), nullable=True),
    sa.Column('user_lga', sa.String(length=100), nullable=True),
    sa.Column('user_password', sa.String(length=225), nullable=False),
    sa.Column('user_usertype', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_user_add'), ['user_add'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_city'), ['user_city'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_email'), ['user_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_fname'), ['user_fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_lga'), ['user_lga'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_lname'), ['user_lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_password'), ['user_password'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_phone'), ['user_phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_profile'), ['user_profile'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_state'), ['user_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_username'), ['user_username'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_usertype'), ['user_usertype'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_user_usertype'))
        batch_op.drop_index(batch_op.f('ix_user_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_user_state'))
        batch_op.drop_index(batch_op.f('ix_user_user_profile'))
        batch_op.drop_index(batch_op.f('ix_user_user_phone'))
        batch_op.drop_index(batch_op.f('ix_user_user_password'))
        batch_op.drop_index(batch_op.f('ix_user_user_lname'))
        batch_op.drop_index(batch_op.f('ix_user_user_lga'))
        batch_op.drop_index(batch_op.f('ix_user_user_fname'))
        batch_op.drop_index(batch_op.f('ix_user_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_user_city'))
        batch_op.drop_index(batch_op.f('ix_user_user_add'))

    op.drop_table('user')
    op.drop_table('adminreg')
    # ### end Alembic commands ###
