"""empty message

Revision ID: 099a45136ef0
Revises: f7d5e913bc94
Create Date: 2024-05-12 13:06:19.950092

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '099a45136ef0'
down_revision = 'f7d5e913bc94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fname', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('lname', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('zipcode', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('ssn', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(length=225), nullable=False))
        batch_op.drop_index('ix_user_user_add')
        batch_op.drop_index('ix_user_user_city')
        batch_op.drop_index('ix_user_user_email')
        batch_op.drop_index('ix_user_user_fname')
        batch_op.drop_index('ix_user_user_lname')
        batch_op.drop_index('ix_user_user_password')
        batch_op.drop_index('ix_user_user_ssn')
        batch_op.drop_index('ix_user_user_zipcode')
        batch_op.create_index(batch_op.f('ix_user_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_fname'), ['fname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_lname'), ['lname'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_password'), ['password'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_ssn'), ['ssn'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_zipcode'), ['zipcode'], unique=False)
        batch_op.drop_column('user_add')
        batch_op.drop_column('user_lname')
        batch_op.drop_column('user_zipcode')
        batch_op.drop_column('user_city')
        batch_op.drop_column('user_ssn')
        batch_op.drop_column('user_email')
        batch_op.drop_column('user_fname')
        batch_op.drop_column('user_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_password', mysql.VARCHAR(length=225), nullable=False))
        batch_op.add_column(sa.Column('user_fname', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('user_email', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_ssn', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('user_city', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('user_zipcode', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('user_lname', mysql.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('user_add', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_index(batch_op.f('ix_user_zipcode'))
        batch_op.drop_index(batch_op.f('ix_user_ssn'))
        batch_op.drop_index(batch_op.f('ix_user_password'))
        batch_op.drop_index(batch_op.f('ix_user_lname'))
        batch_op.drop_index(batch_op.f('ix_user_fname'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_city'))
        batch_op.drop_index(batch_op.f('ix_user_address'))
        batch_op.create_index('ix_user_user_zipcode', ['user_zipcode'], unique=False)
        batch_op.create_index('ix_user_user_ssn', ['user_ssn'], unique=False)
        batch_op.create_index('ix_user_user_password', ['user_password'], unique=False)
        batch_op.create_index('ix_user_user_lname', ['user_lname'], unique=False)
        batch_op.create_index('ix_user_user_fname', ['user_fname'], unique=False)
        batch_op.create_index('ix_user_user_email', ['user_email'], unique=False)
        batch_op.create_index('ix_user_user_city', ['user_city'], unique=False)
        batch_op.create_index('ix_user_user_add', ['user_add'], unique=False)
        batch_op.drop_column('password')
        batch_op.drop_column('ssn')
        batch_op.drop_column('email')
        batch_op.drop_column('zipcode')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')

    # ### end Alembic commands ###
