"""empty message

Revision ID: f7d5e913bc94
Revises: 04b065f92762
Create Date: 2024-05-12 10:31:15.738955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7d5e913bc94'
down_revision = '04b065f92762'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('regdate', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('user_ssn', sa.String(length=50), nullable=True))
        batch_op.alter_column('user_zipcode',
               existing_type=mysql.DATETIME(),
               type_=sa.String(length=64),
               nullable=False)
        batch_op.drop_index('ix_user_user_lga')
        batch_op.drop_index('ix_user_user_phone')
        batch_op.drop_index('ix_user_user_profile')
        batch_op.drop_index('ix_user_user_state')
        batch_op.drop_index('ix_user_user_username')
        batch_op.drop_index('ix_user_user_usertype')
        batch_op.create_index(batch_op.f('ix_user_user_ssn'), ['user_ssn'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_user_zipcode'), ['user_zipcode'], unique=False)
        batch_op.drop_column('user_phone')
        batch_op.drop_column('user_pix')
        batch_op.drop_column('user_state')
        batch_op.drop_column('user_lga')
        batch_op.drop_column('user_profile')
        batch_op.drop_column('user_username')
        batch_op.drop_column('user_usertype')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_usertype', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_username', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_profile', mysql.VARCHAR(length=300), nullable=True))
        batch_op.add_column(sa.Column('user_lga', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_state', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('user_pix', mysql.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('user_phone', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_user_zipcode'))
        batch_op.drop_index(batch_op.f('ix_user_user_ssn'))
        batch_op.create_index('ix_user_user_usertype', ['user_usertype'], unique=False)
        batch_op.create_index('ix_user_user_username', ['user_username'], unique=False)
        batch_op.create_index('ix_user_user_state', ['user_state'], unique=False)
        batch_op.create_index('ix_user_user_profile', ['user_profile'], unique=False)
        batch_op.create_index('ix_user_user_phone', ['user_phone'], unique=False)
        batch_op.create_index('ix_user_user_lga', ['user_lga'], unique=False)
        batch_op.alter_column('user_zipcode',
               existing_type=sa.String(length=64),
               type_=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('user_ssn')
        batch_op.drop_column('regdate')

    # ### end Alembic commands ###
